### ISSUE TITLE
[Feature] Config Models folder

### ISSUE THREAD

**Issue by robsontenorio** [georgyKurian/vscode-laravel-ide-helper#4]
**Is your feature request related to a problem? Please describe.**
Feature

**Describe the solution you'd like**
It would be nice to configure models folder. Currently it does not loopkup for custom folders for Models.

**Additional context**
Laravel IDE Helper, allow us to configure models folder 

https://github.com/barryvdh/laravel-ide-helper/blob/master/config/ide-helper.php#L141

**Comment by ghost** [comment]
Please publish the package config `php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config` and add your models folder in the config

**Comment by robsontenorio** [comment]
Thanks!
